# Generated by Django 3.1.7 on 2021-05-14 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210503_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_paper',
            old_name='qPaperTitle',
            new_name='Question_Paper_Title',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 55, 25, 627666)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 9, 55, 25, 627528)),
        ),
    ]
