# Generated by Django 3.1.7 on 2021-05-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='stream',
        ),
    ]
