# Generated by Django 3.2.5 on 2021-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentinfo_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='picture',
            field=models.ImageField(blank=True, default='/static/image/avatar.svg', upload_to='student_profile_pics'),
        ),
    ]
