# Generated by Django 3.1.7 on 2021-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='student_profile_pics'),
        ),
    ]
